# application-dev.yml
server:
  port: 8513

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.222.23:8848
  data:
    redis:
      host: 172.30.222.23
      port: 6379